<?php
function sandbox_geo_views_api() {
  return array(
    'api' => 2.0,
  );
}

function sandbox_geo_form_views_exposed_form_alter(&$form, &$form_alter) {
  if ($form['#id'] == 'views-exposed-form-locations-page-1') {
    $form['distance']['ricerca_utente'] = array (
      '#type' => 'textfield',
      '#weight' => -100,
      '#title' => 'Ricerca Utente',
    );
  }
}

function sandbox_geo_block ($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $block = array (
      'ricerca_per_provincia' => array (
        'info' => 'Filtra per Provincia',
        'cache' => BLOCK_NO_CACHE,
        //'visibility' => 1,
        //'pages' => 'mappa_ricerca',
      )
    );
  }
  else if ($op == 'view') {
    switch ($delta) {
      case 'ricerca_per_provincia':
        $block = array (
          'subject' => '',
          'content' => '<select class="form-select" id="ricerca-per-provincia" name="province">',
        );
        $block['content'] .= '<option selected="selected" value="">Scegli Provincia</option>';

        module_load_include('inc', 'location', 'supported/location.it');
        $p = location_province_list_it();
        foreach ($p as $k => $v) {
          $block['content'] .= '<option value="' . $v . '">' . $v . '</option>';
        }

        //$query = 'SELECT name, code FROM bauboys_data_province';
        //$result = db_query($query);
        //while (($r = db_fetch_object($result))) {
          //$block['content'] .= '<option value="' . $r->name . '">' . $r->name . '</option>';
        //}

        $block['content'] .= '</select>';
        $block['content'] .= '<input type="submit" value="Scegli" id="submit-ricerca-per-provincia">';
        drupal_add_js(drupal_get_path('module', 'sandbox_geo') . '/js/sandbox_geo.js');
        break;
    }
  }
  return $block;
}
