<?php

function html5_user_geolocation_perm() {
  return array(
    'allow location to be stored',
    'administer location storing'
  );
}

function html5_user_geolocation_menu() {
  return array(
    'admin/settings/html5_user_geolocation' => array(
      'title' => 'HTML5 user geolocation',
      'access arguments' => array('administer location storing'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('html5_user_geolocation_settings_form'),
    ),
  );
}

function html5_user_geolocation_init() {
  drupal_add_css(drupal_get_path('module', 'html5_user_geolocation') . '/html5_user_geolocation.css');
  drupal_add_js(drupal_get_path('module', 'html5_user_geolocation') . '/html5_user_geolocation.js');
  drupal_add_js(array('html5UserGeolocationPrecision' => variable_get('html5_user_geolocation_precision', 1)), 'setting');
}

function html5_user_geolocation_user($op, &$edit, &$account, $category = NULL) {
  global $user;

  switch ($op) {
    case 'form':
      if ($category === 'account' && user_access('allow location to be stored') && $account->uid === $user->uid) {
        $current = db_fetch_object(db_query('SELECT latitude, longitude FROM {html5_user_geolocation} WHERE uid = %d', $account->uid));
        $form = array();
        $form['html5_user_geolocation'] = array(
          '#type' => 'fieldset',
          '#title' => t('Location'),
          '#tree' => TRUE,
        );
        $form['html5_user_geolocation']['save'] = array(
          '#type' => 'checkbox',
          '#title' => t('Save my location'),
          '#description' => variable_get('html5_user_geolocation_why', t('Your location will be saved and may be shared.')),
          '#default_value' => $current !== FALSE,
        );
        $form['html5_user_geolocation']['latitude'] = array(
          '#type' => 'hidden',
          '#default_value' => $current === FALSE ? 0 : $current->latitude,
        );
        $form['html5_user_geolocation']['longitude'] = array(
          '#type' => 'hidden',
          '#default_value' => $current === FALSE ? 0 : $current->longitude,
        );
        $form['html5_user_geolocation']['map'] = array(
          '#type' => 'item',
          '#id' => 'html5-user-geolocation-map',
          '#value' => '<div id="html5-user-geolocation-map"><div class="dot"></div></div>',
          '#description' => t('Saved location is rounded to <span>…</span>km units.'),
        );
        $form['html5_user_geolocation']['messages'] = array(
          '#type' => 'item',
          '#id' => 'html5-user-geolocation-messages',
          '#value' => '<div class="not-supported">' . t('Your web browser does not support this feature.') . '</div>'
            . '<div class="geolocating">Your browser is looking for your location, you may need to approve this…</div>',
        );
        return $form;
      }
      break;

    case 'insert':
    case 'update':
      if (isset($edit['html5_user_geolocation'])) {
        db_query('DELETE FROM {html5_user_geolocation} WHERE uid = %d', $account->uid);
        if ($edit['html5_user_geolocation']['save'] && !empty($edit['html5_user_geolocation']['latitude']) && !empty($edit['html5_user_geolocation']['longitude'])) {
          $edit['html5_user_geolocation']['uid'] = $account->uid;
          $edit['html5_user_geolocation']['latitude'] = round($edit['html5_user_geolocation']['latitude'], variable_get('html5_user_geolocation_precision', 1));
          $edit['html5_user_geolocation']['longitude'] = round($edit['html5_user_geolocation']['longitude'], variable_get('html5_user_geolocation_precision', 1));
          drupal_write_record('html5_user_geolocation', $edit['html5_user_geolocation']);
        }
        $edit['html5_user_geolocation'] = NULL;
      }
      break;
  }
}

function html5_user_geolocation_settings_form() {
  $form = array();
  $form['html5_user_geolocation_precision'] = array(
    '#title' => t('Precision'),
    '#type' => 'select',
    '#description' => t('Round latitude and longitude to this many decimal places.'),
    '#options' => drupal_map_assoc(range(0, 5)),
    '#default_value' => variable_get('html5_user_geolocation_precision', 1),
  );
  $form['html5_user_geolocation_why'] = array(
    '#title' => t('How will user locations be used'),
    '#type' => 'textarea',
    '#description' => t('Users should know why and how their location will be used; see <a href="http://www.w3.org/TR/geolocation-API/#privacy_for_recipients">privacy considerations for recipients of location information</a>.'),
    '#rows' => 2,
    '#default_value' => variable_get('html5_user_geolocation_why', t('Your location will be saved and may be shared.')),
  );
  return system_settings_form($form);
}
